### ISSUE TITLE
compile_quartus.bat 

### ISSUE THREAD

**Issue by justinabate** [pConst/basic_verilog#1]
What is the "pre_flow.tcl" script in [basic_verilog/scripts/compile_quartus.bat](https://github.com/pConst/basic_verilog/blob/master/scripts/compile_quartus.bat) ?

I suspect "post_flow.tcl" is [basic_verilog/scripts/post_flow_quartus.tcl](https://github.com/pConst/basic_verilog/blob/master/scripts/post_flow_quartus.tcl)

**Comment by pConst** [comment]
Hello Justin!

I personally use this one
https://github.com/pConst/basic_verilog/blob/master/scripts/project_version_auto_increment.tcl
as my pre_flow.tcl to increment project version.

73!

чт, 20 янв. 2022 г. в 06:26, Justin Abate ***@***.***>:

**Comment by pConst** [comment]
>
> I suspect "post_flow.tcl" is basic_verilog/scripts/post_flow_quartus.tcl
> <https://github.com/pConst/basic_verilog/blob/master/scripts/post_flow_quartus.tcl>


That`s right

чт, 20 янв. 2022 г. в 06:26, Justin Abate ***@***.***>:
